# Generated by Django 2.2.23 on 2021-08-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilha',
            name='data',
            field=models.TextField(blank=True, max_length=25555, null=True),
        ),
    ]
