# Generated by Django 2.2.23 on 2021-08-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210829_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilha',
            name='data',
            field=models.TextField(blank=True, max_length=2555555555, null=True),
        ),
    ]
